// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp2M7k7TIFo1MNgd12B_s8BnXMpQyjwBc',
    appId: '1:67672893974:web:f91291de206f4709f4e337',
    messagingSenderId: '67672893974',
    projectId: 'prerna-app',
    authDomain: 'prerna-app.firebaseapp.com',
    storageBucket: 'prerna-app.firebasestorage.app',
    measurementId: 'G-GFY8VS2R2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5N-VVDMS2g7dmBgrRzwNUIRESJgK9VZ8',
    appId: '1:67672893974:android:002c169c02a0fa0df4e337',
    messagingSenderId: '67672893974',
    projectId: 'prerna-app',
    storageBucket: 'prerna-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4jFotKquiRIDa6CgAq0QfjubhqHhOiR4',
    appId: '1:67672893974:ios:afcf33ed92c221acf4e337',
    messagingSenderId: '67672893974',
    projectId: 'prerna-app',
    storageBucket: 'prerna-app.firebasestorage.app',
    iosBundleId: 'com.example.prerna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4jFotKquiRIDa6CgAq0QfjubhqHhOiR4',
    appId: '1:67672893974:ios:afcf33ed92c221acf4e337',
    messagingSenderId: '67672893974',
    projectId: 'prerna-app',
    storageBucket: 'prerna-app.firebasestorage.app',
    iosBundleId: 'com.example.prerna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp2M7k7TIFo1MNgd12B_s8BnXMpQyjwBc',
    appId: '1:67672893974:web:41b3d03e9957a808f4e337',
    messagingSenderId: '67672893974',
    projectId: 'prerna-app',
    authDomain: 'prerna-app.firebaseapp.com',
    storageBucket: 'prerna-app.firebasestorage.app',
    measurementId: 'G-92JLG2XKZ8',
  );
}
